
export const LOAD_USER_DATA = "LOAD_USER_DATA";
export const LOAD_POST_DATA = "LOAD_POST_DATA";
export const REMOVE_DATA = "REMOVE_DATA";
export const REQUEST_BEGIN_USERS ="REQUEST_BEGIN_USERS";
export const REQUEST_BEGIN_POSTS ="REQUEST_BEGIN_POSTS";